"""Add page_range to TranslationRecord

Revision ID: 08964c4a7c70
Revises: 
Create Date: 2024-10-11 17:05:17.284563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08964c4a7c70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_range', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_record', schema=None) as batch_op:
        batch_op.drop_column('page_range')

    # ### end Alembic commands ###
