"""empty message

Revision ID: 42178222288a
Revises: 927bf9cb5d9c
Create Date: 2024-10-30 09:18:30.229377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42178222288a'
down_revision = '927bf9cb5d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_ocr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_ocr')

    # ### end Alembic commands ###
