"""Initial migration

Revision ID: 5cb7952cc879
Revises: 
Create Date: 2024-10-26 22:05:00.725373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb7952cc879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('file')
    op.drop_table('translation_record')
    op.drop_table('prompt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('system_message', sa.TEXT(), nullable=False),
    sa.Column('user_message', sa.TEXT(), nullable=False),
    sa.Column('prompt_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('extracted_text', sa.TEXT(), nullable=True),
    sa.Column('translated_text', sa.TEXT(), nullable=True),
    sa.Column('edited_text', sa.TEXT(), nullable=True),
    sa.Column('page_range', sa.VARCHAR(), nullable=True),
    sa.Column('date_at', sa.DATETIME(), nullable=False),
    sa.Column('edited_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filehash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('page_count', sa.INTEGER(), nullable=True),
    sa.Column('page_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('system_prompt', sa.TEXT(), nullable=True),
    sa.Column('user_prompt', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filehash')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
