"""empty message

Revision ID: 71308d97ad4d
Revises: 
Create Date: 2024-10-28 21:55:04.523816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71308d97ad4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filehash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filehash')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_message', sa.Text(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('page_range', sa.String(), nullable=True),
    sa.Column('date_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_record')
    op.drop_table('prompt')
    op.drop_table('file')
    op.drop_table('user')
    # ### end Alembic commands ###
