"""empty message

Revision ID: 927bf9cb5d9c
Revises: 57b15fa0aa47
Create Date: 2024-10-30 08:02:49.472163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927bf9cb5d9c'
down_revision = '57b15fa0aa47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('openai_api_key')

    # ### end Alembic commands ###
