name: CI/CD

on:
  push:
    branches:
      - 'master'

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile.backend
          push: true
          tags: ghcr.io/man0l/tools:backend-latest,ghcr.io/man0l/tools:backend-${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile.frontend.prod
          push: true
          tags: ghcr.io/man0l/tools:frontend-latest,ghcr.io/man0l/tools:frontend-${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
